---
- name: setup webserver
  hosts: all
  become: true
  tasks:
    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
